import { Link } from '@tanstack/react-router'
import { ArrowUpRight, Menu, X, ArrowRight, Phone } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Button } from '@/components/ui/button'
import { contactDetails, navigation } from '@/data/studio'
import logo from '@/assets/jumalogo.png'
export function Brand(){return <Link to="/" className="brand" aria-label="Juma Designs home"><img className="brand-logo" src={logo} alt=""/><span>juma<span className="brand-small">DESIGNS</span></span></Link>}
export function ProjectCTA({children='Start a Project',outline=false}:{children?:React.ReactNode;outline?:boolean}){return <Button variant={outline?'outline':'default'} size="lg" asChild><Link to="/contact" hash="project">{children}<ArrowUpRight size={17}/></Link></Button>}
export function Navbar(){const [open,setOpen]=useState(false);const [scrolled,setScrolled]=useState(false);useEffect(()=>{const fn=()=>setScrolled(window.scrollY>24);fn();window.addEventListener('scroll',fn,{passive:true});return()=>window.removeEventListener('scroll',fn)},[]);return <header className={`navbar ${scrolled?'scrolled':''}`} style={{backdropFilter:'blur(12px)'}}><Brand/><nav className="desktop-nav" aria-label="Main navigation">{navigation.map(([label,to])=><Link key={to} to={to} activeOptions={{exact:true}} activeProps={{className:'nav-active'}}>{label}</Link>)}</nav><div className="nav-actions"><a className="nav-phone" href={`tel:+${contactDetails.whatsapp}`} aria-label={`Call ${contactDetails.phoneDisplay}`} title={`Call ${contactDetails.phoneDisplay}`}><Phone size={16}/></a><ProjectCTA/><Button variant="ghost" size="icon" className="menu-toggle" aria-label={open?'Close menu':'Open menu'} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</Button></div>{open&&<nav className="mobile-nav" aria-label="Mobile navigation">{navigation.map(([label,to])=><Link key={to} to={to} onClick={()=>setOpen(false)}>{label}<ArrowUpRight size={18}/></Link>)}</nav>}</header>}
export function Footer(){return <footer className="footer"><div className="footer-top"><div><Brand/><p>Creative & Digital Solutions<br/>from Ghana.</p><span className="location">Accra, Ghana 🇬🇭</span></div><div><h3>Explore</h3>{navigation.map(([label,to])=><Link key={to} to={to}>{label}</Link>)}</div><div><h3>What we do</h3>{['Web Development','Logo Design','Flyer Design','UI/UX Design'].map(s=><Link key={s} to="/services">{s}</Link>)}</div><div><h3>A good idea starts here.</h3><ProjectCTA/><a href={`tel:+${contactDetails.whatsapp}`}>Call {contactDetails.phoneDisplay}</a><a href={`https://wa.me/${contactDetails.whatsapp}`}>WhatsApp {contactDetails.phoneDisplay}</a></div></div><div className="footer-bottom"><span>© 2026 Juma Designs. All rights reserved.</span><span>Thoughtfully designed. Purposefully built. <ArrowRight size={13}/></span></div></footer>}
