import { useState } from 'react'
import { Link } from '@tanstack/react-router'
import { ArrowUpRight, ArrowRight } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog'
import { projects, type Project } from '@/data/studio'
export function BrowserFrame({project}:{project:Project}){return <div className={`preview-image ${project.category==='Websites'?'browser-frame':''} ${project.category==='UI/UX'?'phone-preview':''}`}>
{project.category==='Websites'&&<div className="browser-bar"><span/><span/><span/><div>{project.name.toLowerCase().replaceAll(' ','')}.com <span className="preview-address">/ preview</span></div></div>}<img src={project.image} alt={`${project.name} supplied design preview`} loading="lazy"/></div>}
export function PortfolioCard({project,onOpen}:{project:Project;onOpen:()=>void}){return <article className={`portfolio-card project-${project.id}`}><Button variant="ghost" className="project-image-button" onClick={onOpen} aria-label={`View ${project.name}`}><BrowserFrame project={project}/><span className="project-hover">View Project <ArrowUpRight/></span></Button><div className="project-caption"><div><span className="eyebrow">{project.category==='Websites'?'WEB DESIGN':project.category.toUpperCase()}</span><h3>{project.name}</h3></div><Button variant="outline" size="icon" onClick={onOpen} aria-label={`Open ${project.name}`}><ArrowUpRight/></Button></div></article>}
export function PortfolioModal({project,onClose}:{project:Project|null;onClose:()=>void}){return <Dialog open={Boolean(project)} onOpenChange={v=>{if(!v)onClose()}}><DialogContent className="portfolio-modal">{project&&<><span className="eyebrow">{project.category} · SUPPLIED PREVIEW</span><DialogTitle>{project.name}</DialogTitle><DialogDescription>{project.description} Project credits and final details to be confirmed.</DialogDescription><div className="modal-images">{(project.images??[project.image]).map((image,i)=><img key={image} src={image} alt={`${project.name} preview ${i+1}`}/>)}</div><div className="service-chips">{project.services.map(s=><span key={s}>{s}</span>)}</div>{project.link&&<Button asChild><a href={project.link} target="_blank" rel="noreferrer">Visit website<ArrowUpRight/></a></Button>}</>}</DialogContent></Dialog>}
export function Portfolio({compact=false,webOnly=false}:{compact?:boolean;webOnly?:boolean}){const [filter,setFilter]=useState('All');const [selected,setSelected]=useState<Project|null>(null);const visible=projects.filter(p=>webOnly?p.category==='Websites':filter==='All'||p.category===filter).slice(0,compact?3:undefined);return <section className="section portfolio-section" id="work"><div className="section-heading"><div><span className="eyebrow">SELECTED WORK</span><h2>{webOnly?<>Websites We’ve Built<span className="accent-dot">.</span></>:<>A Few Things<br/>We’ve <em>Built.</em></>}</h2><p>Real work. Real businesses. Real ideas brought to life.</p></div>{compact&&<Button variant="outline" asChild><Link to="/work">Explore all work<ArrowUpRight/></Link></Button>}</div>{!compact&&!webOnly&&<div className="filter-tabs" aria-label="Filter portfolio">{['All','Websites','UI/UX','Branding','Designs','Flyers'].map(f=><Button key={f} variant={filter===f?'default':'ghost'} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</Button>)}</div>}<div key={filter} className="portfolio-grid animate-enter">{visible.map(p=><PortfolioCard key={p.id} project={p} onOpen={()=>setSelected(p)}/>)}</div><p className="preview-note">Supplied design previews. Project details and credits will be updated.</p><PortfolioModal project={selected} onClose={()=>setSelected(null)}/></section>}
