import { Link } from '@tanstack/react-router'
import { ArrowUpRight, ArrowRight, Code2, PenTool, Image, Figma, Sparkles, Check, Circle } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { projects } from '@/data/studio'
import { ProjectCTA } from './layout'
import { BrowserFrame } from './portfolio'
export function Hero(){const primary=projects[0];const secondary=projects[2];return <section className="hero"><div className="hero-topline"><span><i/> INDEPENDENT CREATIVE & DIGITAL STUDIO</span><span>ACCRA, GHANA <ArrowUpRight size={13}/></span></div><div className="hero-main"><div className="hero-copy"><div className="hero-label"><span className="tiny-star">✳</span> A LITTLE DESIGN. A LOT OF POSSIBILITY.</div><h1>We Design.<br/>We Build.<br/><em>You Grow.</em><span className="hero-star">✳</span></h1><p>Juma Designs is a Ghana-based creative and digital studio helping businesses turn ideas into strong brands, beautiful designs and modern websites.</p><div className="hero-ctas"><ProjectCTA/><Button variant="outline" size="lg" asChild><Link to="/work">View Our Work<ArrowUpRight/></Link></Button></div><div className="hero-footnote"><span className="mini-lines">///</span> GOOD DESIGN IS GOOD BUSINESS.</div></div><div className="hero-composition"><div className="composition-grid"/><div className="floating-tag tag-brand"><PenTool size={15}/> BRANDING <span>↗</span></div><div className="hero-browser">{primary&&<BrowserFrame project={primary}/>}<div className="hero-browser-caption"><span><i/> Thoughtfully designed.</span><ArrowUpRight size={16}/></div></div><div className="small-browser glass">{secondary&&<BrowserFrame project={secondary}/>}</div><div className="floating-tag tag-web"><Code2 size={16}/> WEB DESIGN <span>↗</span></div><div className="floating-tag tag-ui"><Figma size={15}/> UI/UX</div><div className="hero-design-card glass"><div className="design-card-head">A GOOD IDEA,<br/><em>beautifully built.</em><ArrowUpRight/></div><div className="design-swatches"><span/><span/><span/><span/></div><div className="design-card-bottom">GRAPHIC DESIGN <span>01 — 26</span></div></div><div className="experience-tag">DIGITAL EXPERIENCES, MADE HUMAN.</div></div></div><div className="hero-bottom"><span>DESIGN WITH PURPOSE. BUILD WITH CARE.</span><Link to="/work">SCROLL TO DISCOVER <ArrowRight size={14}/></Link></div></section>}
const services=[{name:'Web Development',icon:Code2,description:'Modern responsive websites designed around your business.',price:'GH₵1,500',number:'01'}, {name:'Logo & Brand Identity',icon:PenTool,description:'Professional logos and visual identities that make you recognizable.',price:'GH₵300',number:'02'}, {name:'Flyers & Marketing',icon:Image,description:'Social flyers, promotional graphics and marketing materials that stand out.',price:'GH₵150',number:'03'}, {name:'UI/UX Design',icon:Figma,description:'Clean, intuitive interfaces for websites, apps and digital products.',price:'Custom quote',number:'04'}]
export function ServiceCard({service}:{service:typeof services[number]}){const Icon=service.icon;return <article className="service-card glass"><div className="service-card-top"><Icon size={24}/><span>{service.number}</span></div><h3>{service.name}</h3><p>{service.description}</p><div className="service-card-bottom"><div><span className="starting">{service.number==='04'?'TAILORED TO YOUR PROJECT':'Starting from'}</span><strong>{service.price}</strong></div><Button variant="ghost" size="icon" asChild><Link to="/pricing" aria-label={`View ${service.name} pricing`}><ArrowUpRight/></Link></Button></div><Link to="/pricing" className="service-price-link">View pricing<ArrowRight size={13}/></Link></article>}
export function Services(){return <section className="section services-section"><div className="section-heading"><div><span className="eyebrow">ONE STUDIO. MANY POSSIBILITIES.</span><h2>Everything Your Brand Needs<br/>to Look <em>Better Online.</em></h2></div><p className="heading-side">From a single flyer to a complete business website, we help businesses create professional digital experiences without making the process complicated.</p></div><div className="service-grid">{services.map(s=><ServiceCard key={s.name} service={s}/>)}</div></section>}
export function WebIntro(){return <section className="section web-intro"><span className="eyebrow">WEBSITES THAT WORK AS GOOD AS THEY LOOK</span><div className="section-heading"><h2>Your Business Deserves<br/>More Than a <em>WhatsApp Number.</em></h2><p className="heading-side">We design and build modern, responsive websites that help businesses establish credibility, showcase their work and make it easier for customers to take action.</p></div><div className="web-intro-bottom"><div className="service-chips"><span>Mobile-first</span><span>Custom design</span><span>SEO-ready</span><span>Built for your business</span></div><ProjectCTA>Let’s Talk Websites</ProjectCTA></div></section>}
export function WhyUs(){return <section className="section why-section"><div className="section-heading"><div><span className="eyebrow">SMALL STUDIO. BIG ON THE DETAILS.</span><h2>Why Work <em>With Us?</em></h2></div><p className="heading-side">A thoughtful creative partner.<br/>From your first idea to your next chapter.</p></div><div className="why-grid">{[['Built Around Your Business','We don’t force businesses into generic templates.'],['Fast & Practical','We focus on getting useful work into your hands without unnecessary delays.'],['Design + Technology','One team for both visual design and digital development.'],['Transparent Process','You know what happens next before we move forward.'],['Built For Ghanaian Businesses','Services and pricing designed with the Ghanaian market in mind.']].map(([title,text],i)=><article key={title}><span className="why-number">0{i+1} <ArrowUpRight size={15}/></span><h3>{title}</h3><p>{text}</p></article>)}</div></section>}
export function Testimonials(){return <section className="section testimonials"><div className="section-heading"><div><span className="eyebrow">THE PEOPLE BEHIND THE PROJECTS</span><h2>Good Work. <em>Good Words.</em></h2></div><span className="small-note">Client stories coming soon.</span></div><div className="testimonial-grid">{[1,2,3].map(i=><article className="testimonial-card glass" key={i}><span className="quote-mark">“</span><blockquote>Client testimonial goes here.</blockquote><div className="testimonial-person"><span className="placeholder-avatar">—</span><div><strong>Client Name</strong><p>Business / Company</p></div><span className="placeholder-label">PLACEHOLDER</span></div></article>)}</div></section>}
export function FinalCTA(){return <section className="final-cta"><span className="eyebrow">GOOD THINGS START WITH A CONVERSATION.</span><h2>Your Idea.<br/><em>Our Next Project.</em></h2><ProjectCTA>Let’s Build Something</ProjectCTA><span className="cta-star">✳</span></section>}
